[profile.default]
solc = "0.8.23"
src = 'src'
out = 'dist/contracts'
libs = ['lib']

via_ir = true
optimizer_runs = 1000000
eth-rpc-url = 'https://sepolia.infura.io/v3/YOUR_INFURA_API_KEY'
dotenv = ".env"
remappings = [
    "limit-order-protocol/=lib/cross-chain-swap/lib/limit-order-protocol/",
    "solidity-utils/=lib/cross-chain-swap/lib/solidity-utils/",
    "openzeppelin-contracts/=lib/cross-chain-swap/lib/openzeppelin-contracts/",
    "cross-chain-swap/=lib/cross-chain-swap/contracts/",
    "@1inch/limit-order-protocol-contract/=lib/cross-chain-swap/lib/limit-order-protocol/",
    "@1inch/solidity-utils/=lib/cross-chain-swap/lib/solidity-utils/"
]

fs_permissions = [
    { access = "read", path = "dist/contracts" }, 
    { access = "read-write", path = ".forge-snapshots/" },
    { access = "read-write", path = "." }
]

extra_output = ['storageLayout']